// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: snackinventory.proto

package snackinventory

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Snack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Barcode string `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand   string `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
}

func (x *Snack) Reset() {
	*x = Snack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snackinventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snack) ProtoMessage() {}

func (x *Snack) ProtoReflect() protoreflect.Message {
	mi := &file_snackinventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snack.ProtoReflect.Descriptor instead.
func (*Snack) Descriptor() ([]byte, []int) {
	return file_snackinventory_proto_rawDescGZIP(), []int{0}
}

func (x *Snack) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Snack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Snack) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type CreateSnackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snack *Snack `protobuf:"bytes,1,opt,name=snack,proto3" json:"snack,omitempty"`
}

func (x *CreateSnackRequest) Reset() {
	*x = CreateSnackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snackinventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSnackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnackRequest) ProtoMessage() {}

func (x *CreateSnackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snackinventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnackRequest.ProtoReflect.Descriptor instead.
func (*CreateSnackRequest) Descriptor() ([]byte, []int) {
	return file_snackinventory_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSnackRequest) GetSnack() *Snack {
	if x != nil {
		return x.Snack
	}
	return nil
}

// Status / Success is communicated via gRPC response status.
type CreateSnackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSnackResponse) Reset() {
	*x = CreateSnackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snackinventory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSnackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnackResponse) ProtoMessage() {}

func (x *CreateSnackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snackinventory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnackResponse.ProtoReflect.Descriptor instead.
func (*CreateSnackResponse) Descriptor() ([]byte, []int) {
	return file_snackinventory_proto_rawDescGZIP(), []int{2}
}

var File_snackinventory_proto protoreflect.FileDescriptor

var file_snackinventory_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x6e, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x6e, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x4b, 0x0a, 0x05, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72,
	0x61, 0x6e, 0x64, 0x22, 0x41, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x6e, 0x61,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x6e, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x52,
	0x05, 0x73, 0x6e, 0x61, 0x63, 0x6b, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x6e, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6a, 0x0a,
	0x0e, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x58, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x12, 0x22,
	0x2e, 0x73, 0x6e, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x6e, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6d, 0x62, 0x61, 0x72, 0x72, 0x6f, 0x6e,
	0x2f, 0x53, 0x6e, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snackinventory_proto_rawDescOnce sync.Once
	file_snackinventory_proto_rawDescData = file_snackinventory_proto_rawDesc
)

func file_snackinventory_proto_rawDescGZIP() []byte {
	file_snackinventory_proto_rawDescOnce.Do(func() {
		file_snackinventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_snackinventory_proto_rawDescData)
	})
	return file_snackinventory_proto_rawDescData
}

var file_snackinventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_snackinventory_proto_goTypes = []interface{}{
	(*Snack)(nil),               // 0: snackinventory.Snack
	(*CreateSnackRequest)(nil),  // 1: snackinventory.CreateSnackRequest
	(*CreateSnackResponse)(nil), // 2: snackinventory.CreateSnackResponse
}
var file_snackinventory_proto_depIdxs = []int32{
	0, // 0: snackinventory.CreateSnackRequest.snack:type_name -> snackinventory.Snack
	1, // 1: snackinventory.SnackInventory.CreateSnack:input_type -> snackinventory.CreateSnackRequest
	2, // 2: snackinventory.SnackInventory.CreateSnack:output_type -> snackinventory.CreateSnackResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_snackinventory_proto_init() }
func file_snackinventory_proto_init() {
	if File_snackinventory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snackinventory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snackinventory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSnackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snackinventory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSnackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snackinventory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snackinventory_proto_goTypes,
		DependencyIndexes: file_snackinventory_proto_depIdxs,
		MessageInfos:      file_snackinventory_proto_msgTypes,
	}.Build()
	File_snackinventory_proto = out.File
	file_snackinventory_proto_rawDesc = nil
	file_snackinventory_proto_goTypes = nil
	file_snackinventory_proto_depIdxs = nil
}
